### ISSUE TITLE
Wheres the cart?

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#10]
We need a cart button somewhere, it should come with the theme..

It would be amazing to have a cart summary that actually works and updates on a sidebar, just an idea.

**Comment by mj0y** [comment]
Cart added to the header menu.

**Comment by Ganacontrol** [comment]
When you click on the cart and go to that page.
There is a slight  bug in the Menu. Selected menu item looks odd

**Comment by Ganacontrol** [comment]
slack test

**Comment by Ganacontrol** [comment]
I suggest you can center the cart icon, that will at least make it look better

**Comment by mj0y** [comment]
Fixed? Removed border on menu all together.

**Comment by Ganacontrol** [comment]
Yup, moving to live
