### ISSUE TITLE
Content ideas for about us page

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#11]
Quienes somos needs help. They don't know what to write about there. If we can just come up with the structure or idea they will write it all.

**Comment by mj0y** [comment]
1. What the company is about.
2. What you offer - such as products or services.
+ some other stuff depending on what they actually offer :o No clue what they do.

But you can grab ideas from:
http://fitness.skat.tf/about-us/

**Comment by Ganacontrol** [comment]
I'll assign this to myself and work with the client aabout it
