### ISSUE TITLE
Homepage trainers

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#12]
There should only be one listed trainer in the homepage, the one without picture (for now) that is his girlfriend.

If you click on the link it will take you to the page where we want to offer her coaching services.
That page:
https://suplesmarket.com/wcs3_instructor/jessica-chiu-health-fitness-coach/

Should be the same as

https://suplesmarket.com/servicios/asesoria-para-mujeres

So maybe we need to make a redirect or something to arrange it

**Comment by mj0y** [comment]
Fixed. Only one trainer on the homepage now.

Explain the same page part...? Second link is 404.

**Comment by Ganacontrol** [comment]
Alright so the second link I got it from the Menu under services.

The menu should stay like with those names, but change the URL to for the submenu element
https://suplesmarket.com/wcs3_instructor/jessica-chiu-health-fitness-coach/

**Comment by mj0y** [comment]
That's it? Replaced the link with:
https://suplesmarket.com/wcs3_instructor/jessica-chiu-health-fitness-coach/

**Comment by Ganacontrol** [comment]
Yeah that one the easiest way to fix this, works for me. Not great for SEO but it'll do for now, they didn't pay me for SEO
