### ISSUE TITLE
Website favicon

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#13]
We don't have any designer to help, we just need to shrink the logo somehow to 16x16 or something that looks "OK" as favicon.

**Comment by mj0y** [comment]
Provide me with a bigger image of the logo. There isn't one in Media.

**Comment by Ganacontrol** [comment]
![isologo suples market bicolor-01](https://cloud.githubusercontent.com/assets/16263263/15036749/087c34b2-1259-11e6-9cb6-18db7b5da62e.png)

**Comment by mj0y** [comment]
Done?

**Comment by Ganacontrol** [comment]
Yes,
