### ISSUE TITLE
Add social login buttons for woocommerce

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#14]
I have the plugin for social woocommerce login. We need to set this up to facilitate sign ups and payments.

**Comment by mj0y** [comment]
Added to footer and header. Does the iconosquare need to be added?

**Comment by Ganacontrol** [comment]
Nah, its good as it is. However this issue is about user login, not social media links

**Comment by Ganacontrol** [comment]
I will upload woocommerce plugin for this now one sec

**Comment by Ganacontrol** [comment]
[Woocommerce-social-login.zip](https://github.com/Ganacontrol/cdmx/files/250050/Woocommerce-social-login.zip)

**Comment by mj0y** [comment]
Social login with FB and G+ added to: My Account / Cart / Checkout. 
Looks great and works too! :)
