### ISSUE TITLE
Cart uses cache?

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#16]
Not sure what the problem is but my cart icon keeps saying I have one item on cart  when it's empty.

Maybe installing W3 total cache or something?

**Comment by mj0y** [comment]
Nah. It was the code I was using.
Added cart with a plugin now, check it out?

**Comment by Ganacontrol** [comment]
I see the cart on the sidebar, I think it would be nice to have it on the main menu too  like it was :)

**Comment by mj0y** [comment]
The cart is in the menu however when you're NOT logged in. I've used an IF statement to have 2 menus, depending on if you are logged in or not.
However the stupid cart plugin doesn't allow two menus :( Can we get this plugin maybe:
https://wpovernight.com/downloads/menu-cart-pro/?utm_source=wordpress&utm_medium=menucartfree&utm_campaign=menucartmultiplemenus

**Comment by Ganacontrol** [comment]
I usually am in favor of buying plugins,
But honestly I don't want to spend on silly things like showing the cart.

So to sum this up, we can't show the cart icon to logged in users? That sounds strange.

**Comment by mj0y** [comment]
Well, because its with a plugin which allows to display it on only 1 menu.

You can also contact the theme support and ask them why the fuck there is no mini cart included when there is one on their demo....

**Comment by mj0y** [comment]
Better contact them. I can include a cart redirecting to the cart page, however it wont count the items like in the demo :(

**Comment by Ganacontrol** [comment]
Go ahead and log in to the themeforest account and there is a contact theme owner support button there, write him a message about that. If his answer comes to my email I will forward that to you.

So if I understand correctly, the cart shows up for logged out users but not for logged in? Im sure he will be able to fix that easily.

**Comment by mj0y** [comment]
I'll write him.

The cart shows up that way because of the plugin (not included in the theme).

I can however add the cart that was before, just without the item count until the theme support gets back to us?

**Comment by Ganacontrol** [comment]
Let's wait for his reply first,  its better to always use the theme features before using plugins

**Comment by mj0y** [comment]
Sorry, but that item purchase code has already been registered with another account. Please login to that account to continue, or create a new account with another purchase code.

You already have an account with their forum support. Go ask.

**Comment by Ganacontrol** [comment]
Sorry about that, here are the details of the support account
jorge@coaching.digital
Kokolo123
You go ahead and ask :dancer:  :dash:   :)

**Comment by mj0y** [comment]
Posted. Notify me if there are replies.

**Comment by Ganacontrol** [comment]
Yup will do

**Comment by mj0y** [comment]
Fiiiiixed.
