### ISSUE TITLE
Implement all provided content

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#2]
I will transfer you the files provided by the client.

The main shop will be done when the client delivers the CSV file with all the product details and images.

**Comment by Ganacontrol** [comment]
[Secciones del menú.docx](https://github.com/Ganacontrol/cdmx/files/249988/Secciones.del.menu.docx)

**Comment by mj0y** [comment]
Specify which of those I need to add exactly?

**Comment by Ganacontrol** [comment]
All of them are already on the website except the  shop product categories.

**Comment by mj0y** [comment]
Added product categories.

**Comment by Ganacontrol** [comment]
I have attached a zip with pictures, they just gave me this, it should go inside the "Transformaciones" tab inside Jessica Chiu page
[fotosdetransformaciones.zip](https://github.com/Ganacontrol/cdmx/files/255594/fotosdetransformaciones.zip)

**Comment by Ganacontrol** [comment]
Here I attach even more pictures of Jessica Chiu which should be on her page. 
Not sure where exactly these ones should go but if yout put them in, I'll arrange the order/tab location with her.
[evenmorefotos.zip](https://github.com/Ganacontrol/cdmx/files/256232/evenmorefotos.zip)
[masfotos.zip](https://github.com/Ganacontrol/cdmx/files/256233/masfotos.zip)
[moreandmorephotos.zip](https://github.com/Ganacontrol/cdmx/files/256234/moreandmorephotos.zip)

**Comment by mj0y** [comment]
So where should i add them once i make the tabs?
