### ISSUE TITLE
Distributors own shop

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#3]
There is a section of the website the one for "distributors" that should have a separate shop (perhaps even outside of woocommerce to not mix shopping carts? preferably not! but carts shouldn't be combined.)  
So that section should work on its own for calculations and payments, and needs a minimum order of $10,000 MXN.

**Comment by Ganacontrol** [comment]
https://www.woothemes.com/products/woocommerce-one-page-checkout/

**Comment by mj0y** [comment]
I guess this could work? We'll make it work!
Need the plugin though.

**Comment by Ganacontrol** [comment]
Will talk to the client about paying for this and get back to you

**Comment by Ganacontrol** [comment]
Pregtunas:

El mínimo dijimos que eran $10,000.00 Para los distribuidores, quieres que sea absolutamente separado o podrias permitir que alguien pida $5000 en mercancia nromal y 5mil de los productos de distribuidores?

**Comment by Ganacontrol** [comment]
https://www.woothemes.com/products/minmax-quantities/
https://wordpress.org/plugins/minimum-purchase-for-woocommerce/
http://www.varktech.com/woocommerce/minimum-purchase-pro-for-woocommerce/
