### ISSUE TITLE
Fill slider content

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#4]
Just put in some nice text where there isn't that I can change later to whatever the client wants.

**Comment by mj0y** [comment]
There's already text in the slider though.

**Comment by Ganacontrol** [comment]
Alright you win. I need to get my client to think about what to put here for image/text

**Comment by Ganacontrol** [comment]
I'll assign this to myself and work with the client aabout it

**Comment by Ganacontrol** [comment]
Parece que lo que harán es pedir banners de el catrin
