### ISSUE TITLE
Create tabs for contents of this page

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#5]
They want the content to be displayed on tabs for the diferrent content parts inside this page.

https://suplesmarket.com/wcs3_instructor/jessica-chiu-health-fitness-coach/

This page is about his girlfriend who wants sell fitness coaching. So any ideas here welcome.

Also we need to test the contact form here.

**Comment by Ganacontrol** [comment]
This one is quite easy hehe just look at the shortcodes samples in the theme demo

**Comment by mj0y** [comment]
I know, will do.
