### ISSUE TITLE
Contact page finishing

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#8]
Remove google maps from contact page because there is another section specifically for their locations so here should just be contact form, use captcha and test the contact form

**Comment by mj0y** [comment]
Google Map is removed.
Captcha added.

**Comment by mj0y** [comment]
Need SMTP details for contacto@ganacontrol.com

**Comment by mj0y** [comment]
All good! Set to deliver to contacto@suplesmarket.com
