### ISSUE TITLE
Locations page

### ISSUE THREAD

**Issue by Ganacontrol** [Ganacontrol/cdmx#9]
"Ubicaciones" is the page for their locations.

We need to make the addresses show up with pins on the maps for the addresses we have.

**Comment by mj0y** [comment]
I need the correct addresses.
Should they be pinned on one map or on separate maps, like it is now?

**Comment by Ganacontrol** [comment]
Umm, I would prefer all in one map. 

Here are the corrected addresses:

Alvaro Obregon  #1203 Arbol Grande, Ciudad Madero, Tamaulipas
Segunda avenida #303  Col Loma del Gallo, Ciudad Madero, Tamaulipas

**Comment by mj0y** [comment]
Done I guess. No option at all in the map to have street view :(
